program Example;

uses
  System.StartUpCopy,
  FMX.Forms,
  Form.Main in 'Forms\Form.Main.pas' {Form1},
  SDL.Types in '..\Source\SDL.Types.pas',
  SDL.assert in '..\Source\SDL.assert.pas',
  SDL.asyncio in '..\Source\SDL.asyncio.pas',
  SDL.atomic in '..\Source\SDL.atomic.pas',
  SDL.audio in '..\Source\SDL.audio.pas',
  SDL.bits in '..\Source\SDL.bits.pas',
  SDL.blendmode in '..\Source\SDL.blendmode.pas',
  SDL.camera in '..\Source\SDL.camera.pas',
  SDL.clipboard in '..\Source\SDL.clipboard.pas',
  SDL.error in '..\Source\SDL.error.pas',
  SDL.events in '..\Source\SDL.events.pas',
  SDL_inits in '..\Source\SDL_inits.pas',
  SDL_iostream in '..\Source\SDL_iostream.pas',
  SDL_loadso in '..\Source\SDL_loadso.pas',
  SDL_pixels in '..\Source\SDL_pixels.pas',
  SDL_properties in '..\Source\SDL_properties.pas',
  SDL_rect in '..\Source\SDL_rect.pas',
  SDL.stdinc in '..\Source\SDL.stdinc.pas',
  SDL_surface in '..\Source\SDL_surface.pas',
  SDL_video in '..\Source\SDL_video.pas',
  SDL_keycode in '..\Source\SDL_keycode.pas',
  SDL_scancode in '..\Source\SDL_scancode.pas',
  SDL_keyboard in '..\Source\SDL_keyboard.pas',
  SDL_mouse in '..\Source\SDL_mouse.pas',
  SDL_joystick in '..\Source\SDL_joystick.pas',
  SDL_power in '..\Source\SDL_power.pas',
  SDL_sensor in '..\Source\SDL_sensor.pas',
  SDL.guid in '..\Source\SDL.guid.pas',
  SDL_touch in '..\Source\SDL_touch.pas',
  SDL_pen in '..\Source\SDL_pen.pas',
  SDL_vulkan in '..\Source\SDL_vulkan.pas',
  SDL_metal in '..\Source\SDL_metal.pas',
  SDL_locale in '..\Source\SDL_locale.pas',
  SDL_logs in '..\Source\SDL_logs.pas',
  SDL_mains in '..\Source\SDL_mains.pas',
  SDL_messagebox in '..\Source\SDL_messagebox.pas',
  SDL_misc in '..\Source\SDL_misc.pas',
  SDL_mutex in '..\Source\SDL_mutex.pas',
  SDL_thread in '..\Source\SDL_thread.pas',
  SDL_platform in '..\Source\SDL_platform.pas',
  SDL_process in '..\Source\SDL_process.pas',
  SDL_render in '..\Source\SDL_render.pas',
  SDL_revisions in '..\Source\SDL_revisions.pas',
  SDL_storage in '..\Source\SDL_storage.pas',
  SDL.filesystem in '..\Source\SDL.filesystem.pas',
  SDL.gamepad in '..\Source\SDL.gamepad.pas',
  SDL.gpu in '..\Source\SDL.gpu.pas',
  SDL_time in '..\Source\SDL_time.pas',
  SDL_timer in '..\Source\SDL_timer.pas',
  SDL.version in '..\Source\SDL.version.pas',
  SDL.copying in '..\Source\SDL.copying.pas',
  SDL.cpuinfo in '..\Source\SDL.cpuinfo.pas',
  SDL.dialog in '..\Source\SDL.dialog.pas',
  SDL.egl in '..\Source\SDL.egl.pas',
  SDL.endian in '..\Source\SDL.endian.pas',
  SDL.haptic in '..\Source\SDL.haptic.pas',
  SDL.hidapi in '..\Source\SDL.hidapi.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
